### ISSUE TITLE
Confetti duration

### ISSUE THREAD

**Issue by Romaixn** [ektogamat/r3f-confetti-component#1]
To make the confetti explosion duration work, we need to let the calling component handle the timeout and, consequently, remove the `useEffect` inside the component.

Currently, even when setting a number in the `duration` option, it doesn't alter the confetti explosion duration.

I can create a Pull Request to modify this behavior and allow the parent component to handle the timeout if you wish!

**Comment by ektogamat** [comment]
Hey Romain , I would love that. As you know, my intention is to help other people but my knowledge not always help haha 😄
